// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Args []string `json:"args"`
}

type ListRequset struct {
	Name *string `json:"name"`
}

type BashRequset struct {
	Parameters []string `json:"parameters"`
}

type ResponseMore struct {
	Code    int    `json:"code"`
	Data    string `json:"data"`
	Message string `json:"message"`
}

type Response struct {
	Message string `json:"message"`
}
